### ISSUE TITLE
bash BLOAT!!11

### ISSUE THREAD

**Issue by explosion-mental** [Amarakon55/mstatus#1]
hello, just curious, how is this on performance?
running every milisecond... must be a challange
On another note, I highly reccommend [dwmblocks-async](https://github.com/UtkarshVerma/dwmblocks-async)

**Comment by amarz45** [comment]
I realized that the script does not have any bashisms any more so I changed the shebang to `#!/bin/sh`. You can change how often it runs but I set it to every millisecond because I need the volume to update quickly. I must admit that this is inefficient, as I do not want other things to run every millisecond. It still does not affect my performance in any way. I will check out `dwmblocks-async` to see if that is a better alternative. Thanks for the suggestion!

**Comment by amarz45** [comment]
It seems like setting the update interval in dwmblocks-async does not work. See issue [#27](https://github.com/UtkarshVerma/dwmblocks-async/issues/27).

**Comment by explosion-mental** [comment]
> I need the volume to update quickly

May I ask y? every second will do most of the time. (for me a sweet spot is 10 seconds as the minimum value)

**Comment by explosion-mental** [comment]
> I must admit that this is inefficient, as I do not want other things to run every millisecond. It still does not affect my performance in any way

Hmmm I saw myself doing a similar task as `while (1) ...` while working with `poll.3`, that made my machine turn on the fans... Just pointing that it probably might be unnecessary.

**Comment by amarz45** [comment]
I switched to dwmblocks and I noticed that it starts significantly faster. So thank you for suggesting that to me. However, I will not be abandoning this repository.

**Comment by explosion-mental** [comment]
cool

**Comment by explosion-mental** [comment]
taking the oportunity to:

1. I really like ur writtings, it's very natural for you
2. self-promote :p [demwm](https://github.com/explosion-mental/demwm) (really tho may find it useful)

**Comment by amarz45** [comment]
> taking the oportunity to:
> 
>     1. I really like ur writtings, it's very natural for you
> 
>     2. self-promote :p [demwm](https://github.com/explosion-mental/demwm) (really tho may find it useful)

1. Thank you!
2. demwm looks like an excellent project with a lot of work put into it. But standard DWM with my [patches](https://github.com/amarakon/dotfiles/tree/master/etc/portage/patches/x11-wm/dwm) is satisfactory for me.

**Comment by explosion-mental** [comment]
good, I really reccomend you take a look at more patches. some suggestions: fakefullscreen, scratchpads, dynamic scratchpads, combo, deck layout.
another good proyect [dwm-flexipatch](github.com/bakkeby/dwm-flexipatch/)

**Comment by amarz45** [comment]
I have fullscreen as opposed to fakefullscreen, and I also have deck. The others aren't useful for me but thanks for the suggestions. Also, I do not need dwm-flexipatch because my operating system's (Gentoo) package manager automatically applies patches 😉

**Comment by amarz45** [comment]
Right now I am working on a rewrite of this to C. It runs way faster than this shell script. I also made it update only every second while things that need to be updated instantly (such as volume and keymap) can be updated with a kill signal. I know use dwl instead of dwm so it is intended to work for dwl and the somebar status bar, but you can easily change the code to make it work for dwm. I will upload it to GitHub soon.
